[package]
name = "tokio-rustls"
version = "0.22.0"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tls"
homepage = "https://github.com/tokio-rs/tls"
documentation = "https://docs.rs/tokio-rustls"
readme = "README.md"
description = "Asynchronous TLS/SSL streams for Tokio using Rustls."
categories = ["asynchronous", "cryptography", "network-programming"]
edition = "2018"

[dependencies]
tokio = "1.0"
rustls = { git = "https://github.com/ctz/rustls" }
webpki = "0.22"

[features]
early-data = []
dangerous_configuration = ["rustls/dangerous_configuration"]

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
rustls-pemfile = "0.2"
futures-util = "0.3.1"
lazy_static = "1"
webpki-roots = "0.22"
